### ISSUE TITLE
 APPLICATION HAVE CLOSED UNEXPECTEDLY, CODE: 11

### ISSUE THREAD

**Issue by feicicou** [PredatorCZ/Technyx#1]
Hello my friend, thank you very much for your great work, I tested this tool and gave me this information

**Comment by feicicou** [comment]
Thank you very much for PredatorCZ reply
The latest version is 14.40.33810.0
If you have different version of Visual C++ Redistributable, the program won't work

**Comment by PredatorCZ** [comment]
Just to put things into a perspective.
Sometime in June 2024, microsoft released vcredist/SDK 14.40.33810.0, that broke ABI compatibility for mutex class.
Apps built with SDK version 14.40.33810.0 and later won't work with older versions of vcredist.
